spring:
  datasource:
    url: jdbc:postgresql:${RedNeuronalBDURL}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 600000
  jpa:
    format-sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          javax:
            persistence:
              query:
                timeout: 60000
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_URL:http://localhost:8761/eureka/}
    enabled: ${EUREKA_ENABLED:false}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    api-docs:
      enabled: true
      path: /api-docs

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
