spring:
  application:
    name: microservicio-redneuronal
  datasource:
    url: jdbc:postgresql:${RedNeuronalBDURL:?Variable RedNeuronalBDURL es OBLIGATORIA}
    username: ${DB_USER:?Variable DB_USER es OBLIGATORIA}
    password: ${DB_PASSWORD:?Variable DB_PASSWORD es OBLIGATORIA}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 600000
  jpa:
    format-sql: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: ${SPRING_CONFIG_URL:?Variable SPRING_CONFIG_URL es OBLIGATORIA}
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_URL:?Variable SPRING_EUREKA_URL es OBLIGATORIA}
    enabled: ${EUREKA_ENABLED:?Variable EUREKA_ENABLED es OBLIGATORIA}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    org.springframework.web: WARN
