name: Build Microservicios
run-name: ${{ github.actor }} está construyendo el proyecto 🚀

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código fuente
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 🧹 Maven Clean Install
        run: |
          echo "🔍 Ejecutando Maven Clean Install..."
          mvn -B clean install -DskipTests --file pom.xml
